#!/usr/bin/env python3
# SPDX-FileCopyrightText: 2026 Christoph Maier
# SPDX-License-Identifier: Apache-2.0
"""
Generate parametrized sg13cmos5l ESD clamps as flat GDS + CDL + ngspice.

    python3 gen_clamp.py N 11 D  -o outdir          # sg13cmos5l_Clamp_N11N11D.{gds,cdl,spice}
    python3 gen_clamp.py P 5 0D  -o outdir
    python3 gen_clamp.py N 1-20 D -o outdir         # a range, one file set per cell
    python3 gen_clamp.py --limits                   # legal ng range per family/variant

Needs only the 'klayout' Python module (pip install klayout); no PDK, no GUI.
The GDS is geometry-identical to what the KLayout PCells Clamp_N / Clamp_P
(library SG13_cm_clamps) produce for the same parameters.
"""

import argparse
import os
import sys

import klayout.db as db

sys.path.insert(0, os.path.dirname(os.path.abspath(__file__)))
import clamp_engine as E    # noqa: E402
import clamp_klayout as K   # noqa: E402
import clamp_netlist as N   # noqa: E402
from clamp_refdata import REFDATA  # noqa: E402


def ng_list(s):
    if '-' in s:
        a, b = s.split('-')
        return list(range(int(a), int(b) + 1))
    return [int(x) for x in s.split(',')]


def main():
    ap = argparse.ArgumentParser(description=__doc__, formatter_class=argparse.RawDescriptionHelpFormatter)
    ap.add_argument('family', nargs='?', choices=['N', 'P'])
    ap.add_argument('ng', nargs='?', help='fingers: 8 | 1-20 | 2,5,9')
    ap.add_argument('tie', nargs='?', choices=['D', '0D'], default='D')
    ap.add_argument('-o', '--outdir', default='.')
    ap.add_argument('--one-gds', help='write all cells into this single GDS instead of one file per cell')
    ap.add_argument('--limits', action='store_true', help='print the legal ng range and exit')
    a = ap.parse_args()

    if a.limits:
        for fam in ('N', 'P'):
            for tie in ('D', '0D'):
                refs = sorted(REFDATA[fam][tie]['refs'])
                print('%s %-2s ng = 1..%d   reference cells at ng = %s'
                      % (fam, tie, E.max_ng(fam, tie, REFDATA), refs))
        return
    if not (a.family and a.ng):
        ap.error('family and ng are required')

    os.makedirs(a.outdir, exist_ok=True)
    one = None
    if a.one_gds:
        one = db.Layout()
        one.dbu = 0.001
    spice_all, cdl_all = [], []
    for ng in ng_list(a.ng):
        shapes, texts, p = E.generate(a.family, ng, a.tie, REFDATA)
        name = E.cell_name(a.family, ng, a.tie)
        where = ('reference cell' if not p['interpolated'] else
                 'interpolated' if p['inside'] else 'EXTRAPOLATED beyond the reference cells')
        print('%-28s %s; tie block from %s%s' % (name, where, p['ref_cell'],
                                                  ', strap x = %.3f um' % (p['xs'] / 1e3) if p['xs'] else ''))
        cdl = N.cdl(a.family, ng, a.tie, REFDATA)
        spice = N.ngspice(a.family, ng, a.tie, REFDATA)
        if one is not None:
            K.write_cell(one, one.create_cell(name), shapes, texts)
            cdl_all.append(cdl)
            spice_all.append(spice)
            continue
        ly = db.Layout()
        ly.dbu = 0.001
        K.write_cell(ly, ly.create_cell(name), shapes, texts)
        base = os.path.join(a.outdir, name)
        ly.write(base + '.gds')
        open(base + '.cdl', 'w').write(cdl)
        open(base + '.spice', 'w').write('* %s (generated by gen_clamp.py)\n.global sub!\n\n%s' % (name, spice))
    if one is not None:
        base = os.path.join(a.outdir, os.path.splitext(os.path.basename(a.one_gds))[0])
        one.write(base + '.gds')
        open(base + '.cdl', 'w').write('\n'.join(cdl_all))
        open(base + '.spice', 'w').write('* generated by gen_clamp.py\n.global sub!\n\n' + '\n'.join(spice_all))
        print('wrote', base + '.{gds,cdl,spice}')


if __name__ == '__main__':
    main()
