# SPDX-FileCopyrightText: 2024 IHP PDK Authors
# SPDX-FileCopyrightText: 2026 Christoph Maier
# SPDX-License-Identifier: Apache-2.0
#
# GENERATED by extract_clamp_refdata.py on 2026-09-28 -- do not edit by hand.
# Geometry extracted from the IHP sg13cmos5l_io library cells named in REFS:
#   sg13cmos5l_io.gds  sha256 e6f0d64b53af2f13c34c86bba62d427df0507376913873fe8b3a0e961694935e
#   sg13cmos5l_io.cdl  sha256 52279f2ab3d980d8cf5b5b842515c9302f194230422a1f714ccb490c388d3087
# Units: nm. Item kinds: box (x1,y1,x2,y2), poly ((x,y),...), array (x0,y0,w,h,nx,ny,px,py).
# D refs: tie geometry and tie texts are stored relative to the M2 gate strap x (xs).
#
# ANNOTATED COPY (2026-09-30) of scripts/pcells/clamp_refdata.py. REFDATA and the two
# SOURCE_* values are unchanged (the syntax tree of the data equals the original's); the
# data is laid out one item per line so each item can carry a comment. Line numbers of
# files not in this folder refer to scripts/pcells/ as of 2026-09-30.
#
# HOW THIS DATA RELATES TO THE CODE
#   Written by extract_clamp_refdata.py from IHP's sg13cmos5l_io.gds and .cdl:
#     1. GDS layer/datatype -> the layer/purpose names used here (extract :46-56, LAYERS);
#        the PCell path maps them back through the PDK .lyp, the batch path through
#        clamp_klayout.GDS.
#     2. What clamp_engine.array_shapes + bus_shapes draw is subtracted (extract :230-249).
#        Everything below is therefore exactly what the rules do NOT draw.
#     3. frame: D: what all three reference cells of a family share (extract :253-261);
#               0D: everything outside the tie window W0D (extract :262-269).
#        tie:   the rest; D: stored relative to xs (extract :304).
#        decor: Metal1 pin shapes and texts outside the tie window (extract :286-307).
#        IHP's 'pad' labels are dropped (extract :295-296); clamp_engine.rule_texts
#        draws its own.
#     4. netlist: device values from the cell's .cdl subcircuit (extract :182-196, 250).
#     5. Small square cuts are packed into 'array' items (extract :104-155). The grouping
#        is a side effect of that packing: one array may span both rings.
#   Read by clamp_engine.plan() only (via generate, max_ng, and clamp_netlist.py):
#     frame -> drawn in every cell; refs[ng] -> nearest_ref() picks one reference;
#     xs -> interp() over the D references; tie/tie_texts -> moved to the interpolated xs;
#     decor/decor_texts -> drawn as stored; netlist -> clamp_netlist.py only.
#   Imported by clamp_base_code.py, gen_clamp.py, verify_clamp.py, which pass it to the
#   engine without looking inside.

SOURCE_GDS_SHA256 = 'e6f0d64b53af2f13c34c86bba62d427df0507376913873fe8b3a0e961694935e'
SOURCE_CDL_SHA256 = '52279f2ab3d980d8cf5b5b842515c9302f194230422a1f714ccb490c388d3087'

REFDATA = {
    # ====================================================================================
    # N: NMOS clamp, pad -> iovss, one device row
    'N': {
        # ---- N/0D: gate tied to the rail through an rppd (always-off clamp)
        '0D': {
            # frame: guard rings with their wells, implants and contacts
            'frame': [
                # inner ring: p+ substrate tap, net iovss
                ('Activ', 'drawing', 'poly', ((1800, 1850), (1800, 7810), (2140, 7810), (2140, 2190), (77860, 2190), (77860, 7810), (1800, 7810), (1800, 8150), (78200, 8150), (78200, 1850))),
                # outer ring: n+ active inside the NWell ring (n-type guard ring; no pin in the cell)
                ('Activ', 'drawing', 'poly', ((0, 0), (0, 9560), (340, 9560), (340, 340), (79660, 340), (79660, 9560), (0, 9560), (0, 9900), (80000, 9900), (80000, 0))),
                # ring contacts, Activ to Metal1 of the rings: outer ring left, outer ring right
                ('Cont', 'drawing', 'array', (90, 620, 160, 160, 2, 26, 79660, 340)),
                # ring contacts, Activ to Metal1 of the rings: outer ring bottom, outer ring top
                ('Cont', 'drawing', 'array', (140, 90, 160, 160, 187, 2, 340, 9560)),
                # ring contacts, Activ to Metal1 of the rings: inner ring left, inner ring right
                ('Cont', 'drawing', 'array', (1890, 2370, 160, 160, 2, 16, 76060, 340)),
                # ring contacts, Activ to Metal1 of the rings: inner ring bottom, inner ring top
                ('Cont', 'drawing', 'array', (2010, 1940, 160, 160, 181, 2, 340, 5960)),
                # ring contacts, Activ to Metal1 of the rings: inner ring bottom, inner ring top
                ('Cont', 'drawing', 'array', (68990, 1940, 160, 160, 27, 2, 340, 5960)),
                # ring contacts, Activ to Metal1 of the rings: outer ring bottom, outer ring top
                ('Cont', 'drawing', 'array', (69160, 90, 160, 160, 32, 2, 340, 9560)),
                # Metal1 on the inner ring; the ring contacts above connect it to the active
                ('Metal1', 'drawing', 'poly', ((24795, 1800), (24795, 1850), (1800, 1850), (1800, 7810), (55205, 7810), (55205, 7760), (54995, 7760), (54995, 7810), (52185, 7810), (52185, 7760), (51975, 7760), (51975, 7810), (49165, 7810), (49165, 7760), (48955, 7760), (48955, 7810), (46145, 7810), (46145, 7760), (45935, 7760), (45935, 7810), (43125, 7810), (43125, 7760), (42915, 7760), (42915, 7810), (40105, 7810), (40105, 7760), (39895, 7760), (39895, 7810), (37085, 7810), (37085, 7760), (36875, 7760), (36875, 7810), (34065, 7810), (34065, 7760), (33855, 7760), (33855, 7810), (31045, 7810), (31045, 7760), (30835, 7760), (30835, 7810), (28025, 7810), (28025, 7760), (27815, 7760), (27815, 7810), (25005, 7810), (25005, 7760), (24795, 7760), (24795, 7810), (2140, 7810), (2140, 2190), (77860, 2190), (77860, 7810), (1800, 7810), (1800, 8150), (78200, 8150), (78200, 1850), (66865, 1850), (66865, 1825), (66245, 1825), (66245, 1850), (55205, 1850), (55205, 1800), (54995, 1800), (54995, 1850), (52185, 1850), (52185, 1800), (51975, 1800), (51975, 1850), (49165, 1850), (49165, 1800), (48955, 1800), (48955, 1850), (46145, 1850), (46145, 1800), (45935, 1800), (45935, 1850), (43125, 1850), (43125, 1800), (42915, 1800), (42915, 1850), (40105, 1850), (40105, 1800), (39895, 1800), (39895, 1850), (37085, 1850), (37085, 1800), (36875, 1800), (36875, 1850), (34065, 1850), (34065, 1800), (33855, 1800), (33855, 1850), (31045, 1850), (31045, 1800), (30835, 1800), (30835, 1850), (28025, 1850), (28025, 1800), (27815, 1800), (27815, 1850), (25005, 1850), (25005, 1800))),
                # Metal1 on the outer ring; the ring contacts above connect it to the active
                ('Metal1', 'drawing', 'poly', ((0, 0), (0, 9560), (340, 9560), (340, 340), (79660, 340), (79660, 9560), (0, 9560), (0, 9900), (80000, 9900), (80000, 0))),
                # NWell ring under the outer ring: the n-well of the n-type guard ring
                ('NWell', 'drawing', 'poly', ((-620, -620), (-620, 8940), (960, 8940), (960, 960), (79040, 960), (79040, 8940), (-620, 8940), (-620, 10520), (80620, 10520), (80620, -620))),
                # Substrate marker (40/0) on the inner ring: marks the p+ tap as a ptap1 device for LVS; its area/perimeter are the ptap values in each netlist entry below
                ('Substrate', 'drawing', 'poly', ((1800, 1850), (1800, 7810), (2140, 7810), (2140, 2190), (77860, 2190), (77860, 7810), (1800, 7810), (1800, 8150), (78200, 8150), (78200, 1850))),
                # p+ implant (pSD) of the inner ring; it also covers the rppd strip, which splits its opening in two (the rppd is a p+ poly resistor)
                ('pSD', 'drawing', 'poly', ((1620, 1670), (1620, 7630), (2320, 7630), (2320, 2350), (66125, 2350), (66125, 7630), (66985, 7630), (66985, 2350), (77680, 2350), (77680, 7630), (1620, 7630), (1620, 8330), (78380, 8330), (78380, 1670))),
            ],
            # one entry per IHP reference cell; clamp_engine.nearest_ref() chooses among them
            'refs': {
                20: {
                    # the IHP cell this was cut from; verify_clamp.py compares against it
                    'cell': 'sg13cmos5l_Clamp_N20N0D',
                    'decor': [
                        # ring pin shape (Metal1 pin 8/2), inner ring bottom side, net iovss
                        ('Metal1', 'pin', 'box', (62245, 1850, 62740, 2100)),
                    ],
                    'decor_texts': [
                        # substrate net name on the TEXT layer (63/0), as IHP's cells carry it
                        ('TEXT', 'drawing', 'sub!', 1970, 2020, 0, None, None, 'R0'),
                        # net label iovss (Metal1 text 8/25), on its ring pin shape above
                        ('Metal1', 'text', 'iovss', 62530, 1995, 0, 'center', 'center', 'R0'),
                    ],
                    # from this cell's .subckt in sg13cmos5l_io.cdl; used by clamp_netlist.py only.
                    # mos: one entry per MOS line (P: MP0, MP1), w = total width of all fingers;
                    # diode/rppd: the tie device drawn in 'tie'; ptap: the tap marked by Substrate
                    'netlist': {'mos': [{'l': '600.0n', 'ng': '20', 'w': '88.000u'}], 'ptap': {'A': '55.801p', 'P': '29.88u'}, 'rppd': {'b': '0', 'l': '3.54u', 'sub': 'sub!', 'value': '1.959K', 'w': '500n'}},
                    'tie': [
                        # rppd terminal contact (one per poly head)
                        ('Cont', 'drawing', 'box', (66375, 2820, 66735, 2980)),
                        # rppd terminal contact (one per poly head)
                        ('Cont', 'drawing', 'box', (66375, 6920, 66735, 7080)),
                        # ring contacts that fall inside the 0D tie window (extract_clamp_refdata.py W0D); they belong to the rings and complete the frame contact rows
                        ('Cont', 'drawing', 'array', (63550, 1940, 160, 160, 16, 2, 340, 5960)),
                        # ring contacts that fall inside the 0D tie window (extract_clamp_refdata.py W0D); they belong to the rings and complete the frame contact rows
                        ('Cont', 'drawing', 'array', (63720, 90, 160, 160, 16, 2, 340, 9560)),
                        # extraction block around the rppd
                        ('EXTBlock', 'drawing', 'poly', ((66125, 2570), (66125, 3180), (66105, 3180), (66105, 6720), (66125, 6720), (66125, 7330), (66985, 7330), (66985, 6720), (67005, 6720), (67005, 3180), (66985, 3180), (66985, 2570))),
                        # rppd poly head (terminal)
                        ('GatPoly', 'drawing', 'box', (66305, 2750, 66805, 3180)),
                        # rppd poly head (terminal)
                        ('GatPoly', 'drawing', 'box', (66305, 6720, 66805, 7150)),
                        # rppd body marker (52/0); carries the rppd device label below
                        ('HeatRes', 'drawing', 'box', (66305, 3180, 66805, 6720)),
                        # Metal1 on a poly head
                        ('Metal1', 'drawing', 'box', (66245, 2750, 66865, 3040)),
                        # Metal1 on the upper poly head; clamp_engine.bus_shapes ends the gate bus here (BUS_END_0D)
                        ('Metal1', 'drawing', 'poly', ((66475, 6840), (66475, 6850), (66325, 6850), (66325, 7150), (66475, 7150), (66475, 7370), (66635, 7370), (66635, 7150), (66785, 7150), (66785, 6850), (66635, 6850), (66635, 6840))),
                        # pin shape on an rppd terminal
                        ('Metal1', 'pin', 'box', (66325, 2750, 66785, 3040)),
                        # pin shape on an rppd terminal
                        ('Metal1', 'pin', 'box', (66325, 6850, 66785, 7150)),
                        # M2 jumper from the lower poly head onto the inner ring: ties the gate, through the resistor, to the iovss rail
                        ('Metal2', 'drawing', 'box', (66250, 1825, 66860, 3045)),
                        # rppd body (resistor recognition 128/0); its length is the l in netlist.rppd
                        ('PolyRes', 'drawing', 'box', (66305, 3180, 66805, 6720)),
                        # salicide block over the rppd body
                        ('SalBlock', 'drawing', 'box', (66105, 3180, 67005, 6720)),
                        # Via1 at both ends of the M2 jumper: on the inner ring and on the lower poly head
                        ('Via1', 'drawing', 'array', (66255, 1875, 190, 190, 2, 2, 410, 925)),
                    ],
                    'tie_texts': [
                        # resistor value label (TEXT 63/0); the value is netlist.rppd value
                        ('TEXT', 'drawing', 'rppd r=1.959k', 66555, 4950, 367, 'center', 'center', 'R90'),
                        # device label on the rppd body marker (HeatRes 52/0)
                        ('HeatRes', 'drawing', 'rppd', 66555, 4950, 1, 'center', 'center', 'R0'),
                    ],
                    # 0D: nothing moves; tie and tie_texts x are absolute
                    'xs': None,
                },
            },
        },
        # ---- N/D: gate = 'gate' pin with an antenna diode
        'D': {
            # frame: guard rings with their wells, implants and contacts
            'frame': [
                # inner ring: p+ substrate tap, net iovss
                ('Activ', 'drawing', 'poly', ((1800, 1800), (1800, 7760), (2140, 7760), (2140, 2140), (77860, 2140), (77860, 7760), (1800, 7760), (1800, 8100), (78200, 8100), (78200, 1800))),
                # outer ring: n+ active inside the NWell ring (n-type guard ring; no pin in the cell)
                ('Activ', 'drawing', 'poly', ((0, 0), (0, 9560), (340, 9560), (340, 340), (79660, 340), (79660, 9560), (0, 9560), (0, 9900), (80000, 9900), (80000, 0))),
                # ring contacts, Activ to Metal1 of the rings: inner ring left, outer ring left
                ('Cont', 'drawing', 'array', (90, 2320, 160, 160, 2, 16, 1800, 340)),
                # ring contacts, Activ to Metal1 of the rings: outer ring left, outer ring right
                ('Cont', 'drawing', 'array', (90, 620, 160, 160, 2, 5, 79660, 340)),
                # ring contacts, Activ to Metal1 of the rings: outer ring left, outer ring right
                ('Cont', 'drawing', 'array', (90, 7760, 160, 160, 2, 5, 79660, 340)),
                # ring contacts, Activ to Metal1 of the rings: outer ring bottom, outer ring top
                ('Cont', 'drawing', 'array', (140, 90, 160, 160, 235, 2, 340, 9560)),
                # ring contacts, Activ to Metal1 of the rings: inner ring bottom, inner ring top
                ('Cont', 'drawing', 'array', (2010, 1890, 160, 160, 224, 2, 340, 5960)),
                # ring contacts, Activ to Metal1 of the rings: inner ring right, outer ring right
                ('Cont', 'drawing', 'array', (77950, 2320, 160, 160, 2, 16, 1800, 340)),
                # Metal1 on the inner ring; the ring contacts above connect it to the active
                ('Metal1', 'drawing', 'poly', ((1800, 1800), (1800, 7760), (2140, 7760), (2140, 2140), (77860, 2140), (77860, 7760), (1800, 7760), (1800, 8100), (78200, 8100), (78200, 1800))),
                # Metal1 on the outer ring; the ring contacts above connect it to the active
                ('Metal1', 'drawing', 'poly', ((0, 0), (0, 9560), (340, 9560), (340, 340), (79660, 340), (79660, 9560), (0, 9560), (0, 9900), (80000, 9900), (80000, 0))),
                # NWell ring under the outer ring: the n-well of the n-type guard ring
                ('NWell', 'drawing', 'poly', ((-620, -620), (-620, 8940), (960, 8940), (960, 960), (79040, 960), (79040, 8940), (-620, 8940), (-620, 10520), (80620, 10520), (80620, -620))),
                # Substrate marker (40/0) on the inner ring: marks the p+ tap as a ptap1 device for LVS; its area/perimeter are the ptap values in each netlist entry below
                ('Substrate', 'drawing', 'poly', ((1800, 1800), (1800, 7760), (2140, 7760), (2140, 2140), (77860, 2140), (77860, 7760), (1800, 7760), (1800, 8100), (78200, 8100), (78200, 1800))),
                # p+ implant (pSD) of the inner ring
                ('pSD', 'drawing', 'poly', ((1620, 1620), (1620, 7580), (2320, 7580), (2320, 2320), (77680, 2320), (77680, 7580), (1620, 7580), (1620, 8280), (78380, 8280), (78380, 1620))),
            ],
            # one entry per IHP reference cell; clamp_engine.nearest_ref() chooses among them
            'refs': {
                2: {
                    # the IHP cell this was cut from; verify_clamp.py compares against it
                    'cell': 'sg13cmos5l_Clamp_N2N2D',
                    'decor': [
                        # ring pin shape (Metal1 pin 8/2), inner ring top side, net iovss
                        ('Metal1', 'pin', 'box', (2800, 7800, 4170, 8040)),
                    ],
                    'decor_texts': [
                        # substrate net name on the TEXT layer (63/0), as IHP's cells carry it
                        ('TEXT', 'drawing', 'sub!', 1970, 1970, 0, None, None, 'R0'),
                        # net label iovss (Metal1 text 8/25), on its ring pin shape above
                        ('Metal1', 'text', 'iovss', 3700, 7900, 0, 'center', 'center', 'R0'),
                    ],
                    # from this cell's .subckt in sg13cmos5l_io.cdl; used by clamp_netlist.py only.
                    # mos: one entry per MOS line (P: MP0, MP1), w = total width of all fingers;
                    # diode/rppd: the tie device drawn in 'tie'; ptap: the tap marked by Substrate
                    'netlist': {'diode': {'a': '608.400f', 'l': '780.00n', 'model': 'dantenna', 'p': '3.12u', 'w': '780.00n'}, 'mos': [{'l': '600.0n', 'ng': '2', 'w': '8.8u'}], 'ptap': {'A': '55.801p', 'P': '29.88u'}},
                    'tie': [
                        # antenna diode active, dantenna (n+ in p-substrate); its size is netlist.diode w/l
                        ('Activ', 'drawing', 'box', (-390, 6350, 390, 7130)),
                        # diode contacts, Activ to Metal1
                        ('Cont', 'drawing', 'array', (-250, 6490, 160, 160, 2, 2, 340, 340)),
                        # the diode's Metal1 minus the rule-drawn riser (clamp_engine.bus_shapes, xs +- 105 nm), which connects it to the gate bus
                        ('Metal1', 'drawing', 'poly', ((-300, 6490), (-300, 6990), (-105, 6990), (-105, 6500), (105, 6500), (105, 6990), (300, 6990), (300, 6490))),
                        # M2 strap from the diode up to the top cell edge: the 'gate' terminal
                        ('Metal2', 'drawing', 'box', (-100, 6665, 100, 9900)),
                        # pin shape of the 'gate' strap
                        ('Metal2', 'pin', 'box', (-100, 6665, 100, 9900)),
                        # diode recognition marker (99/31): makes LVS extract the antenna diode
                        ('Recog', 'diode', 'box', (-410, 6330, 410, 7150)),
                        # Via1, diode Metal1 to the M2 strap
                        ('Via1', 'drawing', 'array', (-95, 6715, 190, 190, 1, 2, 0, 410)),
                    ],
                    'tie_texts': [
                        # device label of the antenna diode (TEXT 63/0)
                        ('TEXT', 'drawing', 'dant', 0, 6740, 200, 'center', 'center', 'R0'),
                        # pin label 'gate' on the M2 strap (Metal2 text 10/25)
                        ('Metal2', 'text', 'gate', 0, 8282, 0, None, None, 'R0'),
                    ],
                    # centre x of the M2 gate strap; the x values of tie and tie_texts below are
                    # relative to it; clamp_engine.interp() interpolates it over ng
                    'xs': 20240,
                },
                8: {
                    # the IHP cell this was cut from; verify_clamp.py compares against it
                    'cell': 'sg13cmos5l_Clamp_N8N8D',
                    'decor': [
                        # ring pin shape (Metal1 pin 8/2), inner ring top side, net iovss
                        ('Metal1', 'pin', 'box', (3680, 7850, 4730, 8100)),
                    ],
                    'decor_texts': [
                        # substrate net name on the TEXT layer (63/0), as IHP's cells carry it
                        ('TEXT', 'drawing', 'sub!', 1970, 1970, 0, None, None, 'R0'),
                        # net label iovss (Metal1 text 8/25), on its ring pin shape above
                        ('Metal1', 'text', 'iovss', 4210, 7930, 400, 'center', 'center', 'R0'),
                    ],
                    # from this cell's .subckt in sg13cmos5l_io.cdl; used by clamp_netlist.py only.
                    # mos: one entry per MOS line (P: MP0, MP1), w = total width of all fingers;
                    # diode/rppd: the tie device drawn in 'tie'; ptap: the tap marked by Substrate
                    'netlist': {'diode': {'a': '608.400f', 'l': '780.00n', 'model': 'dantenna', 'p': '3.12u', 'w': '780.00n'}, 'mos': [{'l': '600.0n', 'ng': '8', 'w': '35.2u'}], 'ptap': {'A': '55.801p', 'P': '29.88u'}},
                    'tie': [
                        # antenna diode active, dantenna (n+ in p-substrate); its size is netlist.diode w/l
                        ('Activ', 'drawing', 'box', (-390, 6360, 390, 7140)),
                        # diode contacts, Activ to Metal1
                        ('Cont', 'drawing', 'array', (-250, 6500, 160, 160, 2, 2, 340, 340)),
                        # the diode's Metal1 minus the rule-drawn riser (clamp_engine.bus_shapes, xs +- 105 nm), which connects it to the gate bus
                        ('Metal1', 'drawing', 'box', (-300, 6500, -105, 7000)),
                        # the diode's Metal1 minus the rule-drawn riser (clamp_engine.bus_shapes, xs +- 105 nm), which connects it to the gate bus
                        ('Metal1', 'drawing', 'box', (105, 6500, 300, 7000)),
                        # M2 strap from the diode up to the top cell edge: the 'gate' terminal
                        ('Metal2', 'drawing', 'box', (-100, 6665, 100, 9900)),
                        # pin shape of the 'gate' strap
                        ('Metal2', 'pin', 'box', (-100, 6665, 100, 9900)),
                        # diode recognition marker (99/31): makes LVS extract the antenna diode
                        ('Recog', 'diode', 'box', (-410, 6340, 410, 7160)),
                        # Via1, diode Metal1 to the M2 strap
                        ('Via1', 'drawing', 'array', (-95, 6715, 190, 190, 1, 2, 0, 410)),
                    ],
                    'tie_texts': [
                        # device label of the antenna diode (TEXT 63/0)
                        ('TEXT', 'drawing', 'dant', 0, 6750, 200, 'center', 'center', 'R0'),
                        # pin label 'gate' on the M2 strap (Metal2 text 10/25)
                        ('Metal2', 'text', 'gate', -10, 8510, 400, 'center', 'center', 'R0'),
                    ],
                    # centre x of the M2 gate strap; the x values of tie and tie_texts below are
                    # relative to it; clamp_engine.interp() interpolates it over ng
                    'xs': 17975,
                },
                15: {
                    # the IHP cell this was cut from; verify_clamp.py compares against it
                    'cell': 'sg13cmos5l_Clamp_N15N15D',
                    'decor': [
                        # ring pin shape (Metal1 pin 8/2), inner ring top side, net iovss
                        ('Metal1', 'pin', 'box', (2427, 7781, 4005, 8069)),
                    ],
                    'decor_texts': [
                        # substrate net name on the TEXT layer (63/0), as IHP's cells carry it
                        ('TEXT', 'drawing', 'sub!', 1970, 1970, 0, None, None, 'R0'),
                        # net label iovss (Metal1 text 8/25), on its ring pin shape above
                        ('Metal1', 'text', 'iovss', 3122, 7934, 0, 'center', 'center', 'R0'),
                    ],
                    # from this cell's .subckt in sg13cmos5l_io.cdl; used by clamp_netlist.py only.
                    # mos: one entry per MOS line (P: MP0, MP1), w = total width of all fingers;
                    # diode/rppd: the tie device drawn in 'tie'; ptap: the tap marked by Substrate
                    'netlist': {'diode': {'a': '608.400f', 'l': '780.00n', 'model': 'dantenna', 'p': '3.12u', 'w': '780.00n'}, 'mos': [{'l': '600.0n', 'ng': '15', 'w': '66.000u'}], 'ptap': {'A': '55.801p', 'P': '29.88u'}},
                    'tie': [
                        # antenna diode active, dantenna (n+ in p-substrate); its size is netlist.diode w/l
                        ('Activ', 'drawing', 'box', (-400, 6315, 380, 7095)),
                        # diode contacts, Activ to Metal1
                        ('Cont', 'drawing', 'array', (-260, 6455, 160, 160, 2, 2, 340, 340)),
                        # the diode's Metal1 minus the rule-drawn riser (clamp_engine.bus_shapes, xs +- 105 nm), which connects it to the gate bus
                        ('Metal1', 'drawing', 'poly', ((-310, 6455), (-310, 6955), (-105, 6955), (-105, 6500), (105, 6500), (105, 6955), (290, 6955), (290, 6455))),
                        # M2 strap from the diode up to the top cell edge: the 'gate' terminal
                        ('Metal2', 'drawing', 'box', (-100, 6665, 100, 9900)),
                        # pin shape of the 'gate' strap
                        ('Metal2', 'pin', 'box', (-100, 6665, 100, 9900)),
                        # diode recognition marker (99/31): makes LVS extract the antenna diode
                        ('Recog', 'diode', 'box', (-420, 6295, 400, 7115)),
                        # Via1, diode Metal1 to the M2 strap
                        ('Via1', 'drawing', 'array', (-95, 6715, 190, 190, 1, 2, 0, 410)),
                    ],
                    'tie_texts': [
                        # device label of the antenna diode (TEXT 63/0)
                        ('TEXT', 'drawing', 'dant', -10, 6705, 200, 'center', 'center', 'R0'),
                        # pin label 'gate' on the M2 strap (Metal2 text 10/25)
                        ('Metal2', 'text', 'gate', 0, 8282, 0, None, None, 'R0'),
                    ],
                    # centre x of the M2 gate strap; the x values of tie and tie_texts below are
                    # relative to it; clamp_engine.interp() interpolates it over ng
                    'xs': 15330,
                },
            },
        },
    },
    # ====================================================================================
    # P: PMOS clamp, pad -> iovdd, two stacked device rows (MP0, MP1)
    'P': {
        # ---- P/0D: gate tied to the rail through an rppd (always-off clamp)
        '0D': {
            # frame: guard rings with their wells, implants and contacts
            'frame': [
                # inner ring: n+ tap of the NWell box, net iovdd
                ('Activ', 'drawing', 'poly', ((1800, 1800), (1800, 17120), (2140, 17120), (2140, 2140), (77860, 2140), (77860, 17120), (1800, 17120), (1800, 17460), (78200, 17460), (78200, 1800))),
                # outer ring: p+ substrate tap, net iovss
                ('Activ', 'drawing', 'poly', ((0, 0), (0, 18920), (340, 18920), (340, 340), (79660, 340), (79660, 18920), (0, 18920), (0, 19260), (80000, 19260), (80000, 0))),
                # ring contacts, Activ to Metal1 of the rings: outer ring left, outer ring right
                ('Cont', 'drawing', 'array', (90, 540, 160, 160, 2, 54, 79660, 340)),
                # ring contacts, Activ to Metal1 of the rings: outer ring bottom, outer ring top
                ('Cont', 'drawing', 'array', (140, 90, 160, 160, 187, 2, 340, 18920)),
                # ring contacts, Activ to Metal1 of the rings: inner ring left, inner ring right
                ('Cont', 'drawing', 'array', (1890, 2410, 160, 160, 2, 43, 76060, 340)),
                # ring contacts, Activ to Metal1 of the rings: inner ring bottom, inner ring top
                ('Cont', 'drawing', 'array', (2010, 1890, 160, 160, 181, 2, 340, 15320)),
                # ring contacts, Activ to Metal1 of the rings: inner ring bottom, inner ring top
                ('Cont', 'drawing', 'array', (68990, 1890, 160, 160, 27, 2, 340, 15320)),
                # ring contacts, Activ to Metal1 of the rings: outer ring bottom, outer ring top
                ('Cont', 'drawing', 'array', (69160, 90, 160, 160, 32, 2, 340, 18920)),
                # Metal1 on the inner ring; the ring contacts above connect it to the active
                ('Metal1', 'drawing', 'poly', ((1800, 1800), (1800, 17120), (2140, 17120), (2140, 2140), (77860, 2140), (77860, 17120), (1800, 17120), (1800, 17460), (78200, 17460), (78200, 1800))),
                # Metal1 on the outer ring; the ring contacts above connect it to the active
                ('Metal1', 'drawing', 'poly', ((0, 0), (0, 18920), (340, 18920), (340, 340), (79660, 340), (79660, 18920), (0, 18920), (0, 19260), (80000, 19260), (80000, 0))),
                # NWell box: the n-well of both PMOS rows and the inner (n+ tap) ring. The rule-drawn array NWell (clamp_engine.array_shapes) lies inside it
                ('NWell', 'drawing', 'box', (1180, 1180, 78820, 18080)),
                # Substrate marker (40/0) on the outer ring: marks the p+ tap as a ptap1 device for LVS; its area/perimeter are the ptap values in each netlist entry below
                ('Substrate', 'drawing', 'poly', ((0, 0), (0, 18920), (340, 18920), (340, 340), (79660, 340), (79660, 18920), (0, 18920), (0, 19260), (80000, 19260), (80000, 0))),
                # p+ implant (pSD) of the outer ring
                ('pSD', 'drawing', 'poly', ((-180, -180), (-180, 18740), (520, 18740), (520, 520), (79480, 520), (79480, 18740), (-180, 18740), (-180, 19440), (80180, 19440), (80180, -180))),
            ],
            # one entry per IHP reference cell; clamp_engine.nearest_ref() chooses among them
            'refs': {
                20: {
                    # the IHP cell this was cut from; verify_clamp.py compares against it
                    'cell': 'sg13cmos5l_Clamp_P20N0D',
                    'decor': [
                        # ring pin shape (Metal1 pin 8/2), outer ring bottom side, net iovss
                        ('Metal1', 'pin', 'box', (62520, 90, 63085, 290)),
                        # ring pin shape (Metal1 pin 8/2), inner ring bottom side, net iovdd
                        ('Metal1', 'pin', 'box', (62440, 1890, 62950, 2080)),
                    ],
                    'decor_texts': [
                        # substrate net name on the TEXT layer (63/0), as IHP's cells carry it
                        ('TEXT', 'drawing', 'sub!', 170, 170, 0, None, None, 'R0'),
                        # net label iovdd (Metal1 text 8/25), on its ring pin shape above
                        ('Metal1', 'text', 'iovdd', 62645, 1980, 0, 'center', 'center', 'R0'),
                        # net label iovss (Metal1 text 8/25), on its ring pin shape above
                        ('Metal1', 'text', 'iovss', 62860, 195, 0, 'center', 'center', 'R0'),
                    ],
                    # from this cell's .subckt in sg13cmos5l_io.cdl; used by clamp_netlist.py only.
                    # mos: one entry per MOS line (P: MP0, MP1), w = total width of all fingers;
                    # diode/rppd: the tie device drawn in 'tie'; ptap: the tap marked by Substrate
                    'netlist': {'mos': [{'l': '600.0n', 'ng': '20', 'w': '133.2u'}, {'l': '600.0n', 'ng': '20', 'w': '133.2u'}], 'ptap': {'A': '66.994p', 'P': '32.74u'}, 'rppd': {'b': '0', 'l': '12.9u', 'sub': 'iovdd', 'value': '6.768K', 'w': '500n'}},
                    'tie': [
                        # rppd terminal contact (one per poly head)
                        ('Cont', 'drawing', 'box', (66375, 2820, 66735, 2980)),
                        # rppd terminal contact (one per poly head)
                        ('Cont', 'drawing', 'box', (66375, 16280, 66735, 16440)),
                        # ring contacts that fall inside the 0D tie window (extract_clamp_refdata.py W0D); they belong to the rings and complete the frame contact rows
                        ('Cont', 'drawing', 'array', (63550, 1890, 160, 160, 16, 2, 340, 15320)),
                        # ring contacts that fall inside the 0D tie window (extract_clamp_refdata.py W0D); they belong to the rings and complete the frame contact rows
                        ('Cont', 'drawing', 'array', (63720, 90, 160, 160, 16, 2, 340, 18920)),
                        # extraction block around the rppd
                        ('EXTBlock', 'drawing', 'poly', ((66125, 2570), (66125, 3180), (66105, 3180), (66105, 16080), (66125, 16080), (66125, 16690), (66985, 16690), (66985, 16080), (67005, 16080), (67005, 3180), (66985, 3180), (66985, 2570))),
                        # rppd poly head (terminal)
                        ('GatPoly', 'drawing', 'box', (66305, 2750, 66805, 3180)),
                        # rppd poly head (terminal)
                        ('GatPoly', 'drawing', 'box', (66305, 16080, 66805, 16510)),
                        # rppd body marker (52/0); carries the rppd device label below
                        ('HeatRes', 'drawing', 'box', (66305, 3180, 66805, 16080)),
                        # Metal1 on a poly head
                        ('Metal1', 'drawing', 'box', (66325, 2750, 66785, 3050)),
                        # Metal1 on the upper poly head; clamp_engine.bus_shapes ends the gate bus here (BUS_END_0D)
                        ('Metal1', 'drawing', 'poly', ((66475, 16200), (66475, 16210), (66325, 16210), (66325, 16510), (66475, 16510), (66475, 16730), (66635, 16730), (66635, 16510), (66785, 16510), (66785, 16210), (66635, 16210), (66635, 16200))),
                        # pin shape on an rppd terminal
                        ('Metal1', 'pin', 'box', (66325, 2750, 66785, 3050)),
                        # pin shape on an rppd terminal
                        ('Metal1', 'pin', 'box', (66325, 16210, 66785, 16510)),
                        # M2 jumper from the lower poly head onto the inner ring: ties the gate, through the resistor, to the iovdd rail
                        ('Metal2', 'drawing', 'box', (66250, 1825, 66860, 3045)),
                        # rppd body (resistor recognition 128/0); its length is the l in netlist.rppd
                        ('PolyRes', 'drawing', 'box', (66305, 3180, 66805, 16080)),
                        # salicide block over the rppd body
                        ('SalBlock', 'drawing', 'box', (66105, 3180, 67005, 16080)),
                        # Via1 at both ends of the M2 jumper: on the inner ring and on the lower poly head
                        ('Via1', 'drawing', 'array', (66255, 1875, 190, 190, 2, 2, 410, 930)),
                        # p+ implant over the rppd
                        ('pSD', 'drawing', 'box', (66125, 2570, 66985, 16690)),
                    ],
                    'tie_texts': [
                        # resistor value label (TEXT 63/0); the value is netlist.rppd value
                        ('TEXT', 'drawing', 'rppd r=6.768k', 66555, 9630, 375, 'center', 'center', 'R90'),
                        # device label on the rppd body marker (HeatRes 52/0)
                        ('HeatRes', 'drawing', 'rppd', 66555, 9630, 1, 'center', 'center', 'R0'),
                    ],
                    # 0D: nothing moves; tie and tie_texts x are absolute
                    'xs': None,
                },
            },
        },
        # ---- P/D: gate = 'gate' pin with an antenna diode
        'D': {
            # frame: guard rings with their wells, implants and contacts
            'frame': [
                # inner ring: n+ tap of the NWell box, net iovdd
                ('Activ', 'drawing', 'poly', ((1800, 1800), (1800, 17120), (2140, 17120), (2140, 2140), (77860, 2140), (77860, 17120), (1800, 17120), (1800, 17460), (78200, 17460), (78200, 1800))),
                # outer ring: p+ substrate tap, net iovss
                ('Activ', 'drawing', 'poly', ((0, 0), (0, 18920), (340, 18920), (340, 340), (79660, 340), (79660, 18920), (0, 18920), (0, 19260), (80000, 19260), (80000, 0))),
                # ring contacts, Activ to Metal1 of the rings: outer ring left, outer ring right
                ('Cont', 'drawing', 'array', (90, 540, 160, 160, 2, 54, 79660, 340)),
                # ring contacts, Activ to Metal1 of the rings: outer ring bottom, outer ring top
                ('Cont', 'drawing', 'array', (140, 90, 160, 160, 235, 2, 340, 18920)),
                # ring contacts, Activ to Metal1 of the rings: inner ring left, inner ring right
                ('Cont', 'drawing', 'array', (1890, 2410, 160, 160, 2, 43, 76060, 340)),
                # ring contacts, Activ to Metal1 of the rings: inner ring bottom, inner ring top
                ('Cont', 'drawing', 'array', (2010, 1890, 160, 160, 224, 2, 340, 15320)),
                # Metal1 on the inner ring; the ring contacts above connect it to the active
                ('Metal1', 'drawing', 'poly', ((1800, 1800), (1800, 17120), (2140, 17120), (2140, 2140), (77860, 2140), (77860, 17120), (1800, 17120), (1800, 17460), (78200, 17460), (78200, 1800))),
                # Metal1 on the outer ring; the ring contacts above connect it to the active
                ('Metal1', 'drawing', 'poly', ((0, 0), (0, 18920), (340, 18920), (340, 340), (79660, 340), (79660, 18920), (0, 18920), (0, 19260), (80000, 19260), (80000, 0))),
                # NWell box: the n-well of both PMOS rows and the inner (n+ tap) ring. The rule-drawn array NWell (clamp_engine.array_shapes) lies inside it
                ('NWell', 'drawing', 'box', (1180, 1180, 78820, 18080)),
                # Substrate marker (40/0) on the outer ring: marks the p+ tap as a ptap1 device for LVS; its area/perimeter are the ptap values in each netlist entry below
                ('Substrate', 'drawing', 'poly', ((0, 0), (0, 18920), (340, 18920), (340, 340), (79660, 340), (79660, 18920), (0, 18920), (0, 19260), (80000, 19260), (80000, 0))),
                # p+ implant (pSD) of the outer ring
                ('pSD', 'drawing', 'poly', ((-180, -180), (-180, 18740), (520, 18740), (520, 520), (79480, 520), (79480, 18740), (-180, 18740), (-180, 19440), (80180, 19440), (80180, -180))),
            ],
            # one entry per IHP reference cell; clamp_engine.nearest_ref() chooses among them
            'refs': {
                2: {
                    # the IHP cell this was cut from; verify_clamp.py compares against it
                    'cell': 'sg13cmos5l_Clamp_P2N2D',
                    'decor': [
                        # ring pin shape (Metal1 pin 8/2), outer ring bottom side, net iovss
                        ('Metal1', 'pin', 'box', (3730, 40, 5150, 270)),
                        # ring pin shape (Metal1 pin 8/2), inner ring top side, net iovdd
                        ('Metal1', 'pin', 'box', (2550, 17150, 4130, 17410)),
                    ],
                    'decor_texts': [
                        # substrate net name on the TEXT layer (63/0), as IHP's cells carry it
                        ('TEXT', 'drawing', 'sub!', 170, 170, 0, None, None, 'R0'),
                        # net label iovdd (Metal1 text 8/25), on its ring pin shape above
                        ('Metal1', 'text', 'iovdd', 3480, 17300, 0, 'center', 'center', 'R0'),
                        # net label iovss (Metal1 text 8/25), on its ring pin shape above
                        ('Metal1', 'text', 'iovss', 4440, 140, 0, 'center', 'center', 'R0'),
                    ],
                    # from this cell's .subckt in sg13cmos5l_io.cdl; used by clamp_netlist.py only.
                    # mos: one entry per MOS line (P: MP0, MP1), w = total width of all fingers;
                    # diode/rppd: the tie device drawn in 'tie'; ptap: the tap marked by Substrate
                    'netlist': {'diode': {'a': '230.4f', 'l': '480n', 'model': 'dpantenna', 'p': '1.92u', 'w': '480n'}, 'mos': [{'l': '600.0n', 'ng': '2', 'w': '13.32u'}, {'l': '600.0n', 'ng': '2', 'w': '13.32u'}], 'ptap': {'A': '66.994p', 'P': '32.74u'}},
                    'tie': [
                        # antenna diode active, dpantenna (p+ in the NWell box); its size is netlist.diode w/l
                        ('Activ', 'drawing', 'box', (-240, 15830, 240, 16310)),
                        # diode contacts, Activ to Metal1
                        ('Cont', 'drawing', 'array', (-80, 15990, 160, 160, 1, 1, 0, 0)),
                        # sliver of the diode's Metal1 beside the rule-drawn riser (clamp_engine.bus_shapes, xs +- 105 nm); the riser fills the gap between the two slivers
                        ('Metal1', 'drawing', 'box', (-130, 15990, -105, 16150)),
                        # sliver of the diode's Metal1 beside the rule-drawn riser (clamp_engine.bus_shapes, xs +- 105 nm); the riser fills the gap between the two slivers
                        ('Metal1', 'drawing', 'box', (105, 15990, 130, 16150)),
                        # pin shape on the diode Metal1 (present only in this IHP cell)
                        ('Metal1', 'pin', 'box', (-130, 15990, 130, 16150)),
                        # M2 strap from the diode up to the top cell edge: the 'gate' terminal
                        ('Metal2', 'drawing', 'box', (-100, 16025, 100, 19260)),
                        # pin shape of the 'gate' strap
                        ('Metal2', 'pin', 'box', (-100, 16025, 100, 19260)),
                        # diode recognition marker (99/31): makes LVS extract the antenna diode
                        ('Recog', 'diode', 'box', (-260, 15810, 260, 16330)),
                        # Via1, diode Metal1 to the M2 strap
                        ('Via1', 'drawing', 'array', (-95, 16075, 190, 190, 1, 2, 0, 410)),
                        # p+ implant of the diode
                        ('pSD', 'drawing', 'box', (-420, 15650, 420, 16490)),
                    ],
                    'tie_texts': [
                        # device label of the antenna diode (TEXT 63/0)
                        ('TEXT', 'drawing', 'dpant', 0, 16070, 200, 'center', 'center', 'R0'),
                        # pin label 'gate' on the M2 strap (Metal2 text 10/25)
                        ('Metal2', 'text', 'gate', 0, 17643, 0, None, None, 'R0'),
                    ],
                    # centre x of the M2 gate strap; the x values of tie and tie_texts below are
                    # relative to it; clamp_engine.interp() interpolates it over ng
                    'xs': 20240,
                },
                8: {
                    # the IHP cell this was cut from; verify_clamp.py compares against it
                    'cell': 'sg13cmos5l_Clamp_P8N8D',
                    'decor': [
                        # ring pin shape (Metal1 pin 8/2), inner ring top side, net iovdd
                        ('Metal1', 'pin', 'box', (5405, 17120, 7675, 17460)),
                        # ring pin shape (Metal1 pin 8/2), outer ring top side, net iovss
                        ('Metal1', 'pin', 'box', (5260, 18920, 7525, 19260)),
                    ],
                    'decor_texts': [
                        # substrate net name on the TEXT layer (63/0), as IHP's cells carry it
                        ('TEXT', 'drawing', 'sub!', 170, 170, 0, None, None, 'R0'),
                        # net label iovss (Metal1 text 8/25), on its ring pin shape above
                        ('Metal1', 'text', 'iovss', 6420, 19090, 400, 'center', 'center', 'R0'),
                        # net label iovdd (Metal1 text 8/25), on its ring pin shape above
                        ('Metal1', 'text', 'iovdd', 6590, 17290, 400, 'center', 'center', 'R0'),
                    ],
                    # from this cell's .subckt in sg13cmos5l_io.cdl; used by clamp_netlist.py only.
                    # mos: one entry per MOS line (P: MP0, MP1), w = total width of all fingers;
                    # diode/rppd: the tie device drawn in 'tie'; ptap: the tap marked by Substrate
                    'netlist': {'diode': {'a': '230.4f', 'l': '480n', 'model': 'dpantenna', 'p': '1.92u', 'w': '480n'}, 'mos': [{'l': '600.0n', 'ng': '8', 'w': '53.28u'}, {'l': '600.0n', 'ng': '8', 'w': '53.28u'}], 'ptap': {'A': '66.994p', 'P': '32.74u'}},
                    'tie': [
                        # antenna diode active, dpantenna (p+ in the NWell box); its size is netlist.diode w/l
                        ('Activ', 'drawing', 'box', (-235, 15860, 245, 16340)),
                        # diode contacts, Activ to Metal1
                        ('Cont', 'drawing', 'array', (-75, 16020, 160, 160, 1, 1, 0, 0)),
                        # sliver of the diode's Metal1 beside the rule-drawn riser (clamp_engine.bus_shapes, xs +- 105 nm); the riser fills the gap between the two slivers
                        ('Metal1', 'drawing', 'box', (-125, 16020, -105, 16180)),
                        # sliver of the diode's Metal1 beside the rule-drawn riser (clamp_engine.bus_shapes, xs +- 105 nm); the riser fills the gap between the two slivers
                        ('Metal1', 'drawing', 'box', (105, 16020, 135, 16180)),
                        # M2 strap from the diode up to the top cell edge: the 'gate' terminal
                        ('Metal2', 'drawing', 'box', (-100, 16025, 100, 19260)),
                        # pin shape of the 'gate' strap
                        ('Metal2', 'pin', 'box', (-100, 16025, 100, 19260)),
                        # diode recognition marker (99/31): makes LVS extract the antenna diode
                        ('Recog', 'diode', 'box', (-255, 15840, 265, 16360)),
                        # Via1, diode Metal1 to the M2 strap
                        ('Via1', 'drawing', 'array', (-95, 16075, 190, 190, 1, 2, 0, 410)),
                        # p+ implant of the diode
                        ('pSD', 'drawing', 'box', (-415, 15680, 425, 16520)),
                    ],
                    'tie_texts': [
                        # device label of the antenna diode (TEXT 63/0)
                        ('TEXT', 'drawing', 'dpant', 5, 16100, 200, 'center', 'center', 'R0'),
                        # pin label 'gate' on the M2 strap (Metal2 text 10/25)
                        ('Metal2', 'text', 'gate', 0, 17643, 0, None, None, 'R0'),
                    ],
                    # centre x of the M2 gate strap; the x values of tie and tie_texts below are
                    # relative to it; clamp_engine.interp() interpolates it over ng
                    'xs': 17975,
                },
                15: {
                    # the IHP cell this was cut from; verify_clamp.py compares against it
                    'cell': 'sg13cmos5l_Clamp_P15N15D',
                    'decor': [
                        # ring pin shape (Metal1 pin 8/2), inner ring top side, net iovdd
                        ('Metal1', 'pin', 'box', (2606, 17184, 3819, 17399)),
                        # ring pin shape (Metal1 pin 8/2), outer ring top side, net iovss
                        ('Metal1', 'pin', 'box', (865, 18957, 2202, 19198)),
                    ],
                    'decor_texts': [
                        # substrate net name on the TEXT layer (63/0), as IHP's cells carry it
                        ('TEXT', 'drawing', 'sub!', 170, 170, 0, None, None, 'R0'),
                        # net label iovdd (Metal1 text 8/25), on its ring pin shape above
                        ('Metal1', 'text', 'iovdd', 3435, 17287, 0, 'center', 'center', 'R0'),
                        # net label iovss (Metal1 text 8/25), on its ring pin shape above
                        ('Metal1', 'text', 'iovss', 1669, 19089, 0, 'center', 'center', 'R0'),
                    ],
                    # from this cell's .subckt in sg13cmos5l_io.cdl; used by clamp_netlist.py only.
                    # mos: one entry per MOS line (P: MP0, MP1), w = total width of all fingers;
                    # diode/rppd: the tie device drawn in 'tie'; ptap: the tap marked by Substrate
                    'netlist': {'diode': {'a': '608.400f', 'l': '780.00n', 'model': 'dpantenna', 'p': '3.12u', 'w': '780.00n'}, 'mos': [{'l': '600.0n', 'ng': '15', 'w': '99.9u'}, {'l': '600.0n', 'ng': '15', 'w': '99.9u'}], 'ptap': {'A': '66.994p', 'P': '32.74u'}},
                    'tie': [
                        # antenna diode active, dpantenna (p+ in the NWell box); its size is netlist.diode w/l
                        ('Activ', 'drawing', 'box', (-370, 15710, 410, 16490)),
                        # diode contacts, Activ to Metal1
                        ('Cont', 'drawing', 'array', (-230, 15850, 160, 160, 2, 2, 340, 340)),
                        # the diode's Metal1 minus the rule-drawn riser (clamp_engine.bus_shapes, xs +- 105 nm), which connects it to the gate bus
                        ('Metal1', 'drawing', 'poly', ((-280, 15850), (-280, 16350), (-105, 16350), (-105, 15860), (105, 15860), (105, 16350), (320, 16350), (320, 15850))),
                        # M2 strap from the diode up to the top cell edge: the 'gate' terminal
                        ('Metal2', 'drawing', 'box', (-100, 16025, 100, 19260)),
                        # pin shape of the 'gate' strap
                        ('Metal2', 'pin', 'box', (-100, 16025, 100, 19260)),
                        # diode recognition marker (99/31): makes LVS extract the antenna diode
                        ('Recog', 'diode', 'poly', ((-390, 15690), (-390, 16510), (-170, 16510), (-170, 16530), (170, 16530), (170, 16510), (430, 16510), (430, 15690))),
                        # Via1, diode Metal1 to the M2 strap
                        ('Via1', 'drawing', 'array', (-95, 16120, 190, 190, 1, 2, 0, 480)),
                        # p+ implant of the diode
                        ('pSD', 'drawing', 'box', (-550, 15530, 590, 16670)),
                    ],
                    'tie_texts': [
                        # device label of the antenna diode (TEXT 63/0)
                        ('TEXT', 'drawing', 'dpant', 20, 16100, 200, 'center', 'center', 'R0'),
                        # pin label 'gate' on the M2 strap (Metal2 text 10/25)
                        ('Metal2', 'text', 'gate', 0, 17643, 0, None, None, 'R0'),
                    ],
                    # centre x of the M2 gate strap; the x values of tie and tie_texts below are
                    # relative to it; clamp_engine.interp() interpolates it over ng
                    'xs': 15330,
                },
            },
        },
    },
}
